# 라이브러리

In [5]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib as mpl

print(np.__version__)
print(pd.__version__)
print(sns.__version__)
print(mpl.__version__)

2.2.4
2.2.3
0.13.2
3.10.1

# 샘플 데이터 가져오기

In [6]:
iris = sns.load_dataset("iris")
iris

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [7]:
iris.head(1)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa

In [8]:
# tips 데이터 = 레스토랑에서 팁주는 사람들의 데이터
tips = sns.load_dataset("tips")
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [9]:
tips.head(1)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2

# 결측치 확인

In [10]:
iris.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [11]:
iris.shape

(150, 5)

In [12]:
tips.shape

(244, 7)

In [13]:
a = tips['day']
type(a)

pandas.core.series.Series

In [14]:
type(tips)

pandas.core.frame.DataFrame

In [15]:
tips['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

# 상위 5개만 보기

In [16]:
# 숫자열을 sort() 내림차순 정렬
# 상위 5개만 인덱싱
iris.nlargest(5, "sepal_length")

     sepal_length  sepal_width  petal_length  petal_width    species
131           7.9          3.8           6.4          2.0  virginica
117           7.7          3.8           6.7          2.2  virginica
118           7.7          2.6           6.9          2.3  virginica
122           7.7          2.8           6.7          2.0  virginica
135           7.7          3.0           6.1          2.3  virginica

# 필터링
 - numpy와 문법 동일

In [17]:
# tips의 평균 구하기
# 평균 보다 큰 데이터만 조회

mean_tip = tips['tip'].mean()
tips[tips["tip"] > mean_tip]

     total_bill   tip     sex smoker   day    time  size
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
5         25.29  4.71    Male     No   Sun  Dinner     4
7         26.88  3.12    Male     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
232       11.61  3.39    Male     No   Sat  Dinner     2
234       15.53  3.00    Male    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
243       18.78  3.00  Female     No  Thur  Dinner     2

[121 rows x 7 columns]

- somker가 no인 것만 조회

In [18]:
tips[tips['smoker'] == 'No']

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
235       10.07  1.25    Male     No   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[151 rows x 7 columns]

In [19]:
tips[tips['time'] == 'Dinner']

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[176 rows x 7 columns]

In [22]:
tips[tips['day'] == 'Sat'].shape

(87, 7)

In [25]:
tips[tips['day'] == 'Sat'].reset_index(drop=True).head(5)

   total_bill   tip     sex smoker  day    time  size
0       20.65  3.35    Male     No  Sat  Dinner     3
1       17.92  4.08    Male     No  Sat  Dinner     2
2       20.29  2.75  Female     No  Sat  Dinner     2
3       15.77  2.23  Female     No  Sat  Dinner     2
4       39.42  7.58    Male     No  Sat  Dinner     4

# loc vs iloc
 - 코드 비교

In [26]:
tips[tips['day'] == 'Sat'].reset_index(drop=True).head(1)

   total_bill   tip   sex smoker  day    time  size
0       20.65  3.35  Male     No  Sat  Dinner     3

In [29]:
# loc
# tips.loc[행, 열]

tips.loc[0:2, ['total_bill', 'tip', 'day']]

   total_bill   tip  day
0       16.99  1.01  Sun
1       10.34  1.66  Sun
2       21.01  3.50  Sun

In [32]:
# iloc
# tips

tips.iloc[0:2, [0, 1, 4]]

   total_bill   tip  day
0       16.99  1.01  Sun
1       10.34  1.66  Sun

In [38]:
tips.loc[tips['day'] == 'Sat', ['total_bill', 'tip', 'day']].reset_index(drop = True).head(1)

   total_bill   tip  day
0       20.65  3.35  Sat

In [41]:
# total_bill 11 이하인것만 조회
tips.loc[tips['total_bill'] <= 11, :].reset_index(drop = True)

    total_bill   tip     sex smoker   day    time  size
0        10.34  1.66    Male     No   Sun  Dinner     3
1         8.77  2.00    Male     No   Sun  Dinner     2
2        10.27  1.71    Male     No   Sun  Dinner     2
3        10.33  1.67  Female     No   Sun  Dinner     3
4         9.55  1.45    Male     No   Sat  Dinner     2
5         9.68  1.32    Male     No   Sun  Dinner     2
6        10.29  2.60  Female     No   Sun  Dinner     2
7         9.94  1.56    Male     No   Sun  Dinner     2
8         3.07  1.00  Female    Yes   Sat  Dinner     1
9        10.51  1.25    Male     No   Sat  Dinner     2
10       10.07  1.83  Female     No  Thur   Lunch     1
11        5.75  1.00  Female    Yes   Fri  Dinner     2
12        7.25  1.00  Female     No   Sat  Dinner     1
13       10.65  1.50  Female     No  Thur   Lunch     2
14        8.52  1.48    Male     No  Thur   Lunch     2
15        8.51  1.25  Female     No  Thur   Lunch     2
16       10.33  2.00  Female     No  Thur   Lunch     2
17        8.35  1.50  Female     No  Thur   Lunch     2
18        9.78  1.73    Male     No  Thur   Lunch     2
19        7.51  2.00    Male     No  Thur   Lunch     2
20       10.59  1.61  Female    Yes   Sat  Dinner     2
21       10.63  2.00  Female    Yes   Sat  Dinner     2
22        7.25  5.15    Male    Yes   Sun  Dinner     2
23        9.60  4.00  Female    Yes   Sun  Dinner     2
24        7.56  1.44    Male     No  Thur   Lunch     2
25       10.34  2.00    Male    Yes  Thur   Lunch     2
26        7.74  1.44    Male    Yes   Sat  Dinner     2
27        8.58  1.92    Male    Yes   Fri   Lunch     1
28       10.09  2.00  Female    Yes   Fri   Lunch     2
29       10.77  1.47    Male     No   Sat  Dinner     2
30       10.07  1.25    Male     No   Sat  Dinner     2

In [45]:
# time가 dinner인 것만 조회
tips.loc[tips['time'] == "Dinner", :].reset_index(drop = True)

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
171       29.03  5.92    Male     No   Sat  Dinner     3
172       27.18  2.00  Female    Yes   Sat  Dinner     2
173       22.67  2.00    Male    Yes   Sat  Dinner     2
174       17.82  1.75    Male     No   Sat  Dinner     2
175       18.78  3.00  Female     No  Thur  Dinner     2

[176 rows x 7 columns]

In [ ]:
# time이 Dinner이면서 total_bill이 11이하인 것만 조회

In [52]:
iris.head(1)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa

In [59]:
iris.loc[(iris['species'] == "virginica") |
(iris['sepal_length'] >= 5), ["sepal_length", "petal_length", "species"]].reset_index(drop = True).head()

   sepal_length  petal_length species
0           5.1           1.4  setosa
1           5.0           1.4  setosa
2           5.4           1.7  setosa
3           5.0           1.5  setosa
4           5.4           1.5  setosa

In [2]:
import seaborn as sns
import pandas as pd

iris = sns.load_dataset("iris")
result = iris.loc[:,["sepal_length", "species"]]
result

     sepal_length    species
0             5.1     setosa
1             4.9     setosa
2             4.7     setosa
3             4.6     setosa
4             5.0     setosa
..            ...        ...
145           6.7  virginica
146           6.3  virginica
147           6.5  virginica
148           6.2  virginica
149           5.9  virginica

[150 rows x 2 columns]

In [5]:
# 파일 내보내기
result.to_csv("dataset/iris_result.csv", index=False)

In [7]:
# 파일 불러오기
iris_df = pd.read_csv("dataset/iris_result.csv")
iris_df

     sepal_length    species
0             5.1     setosa
1             4.9     setosa
2             4.7     setosa
3             4.6     setosa
4             5.0     setosa
..            ...        ...
145           6.7  virginica
146           6.3  virginica
147           6.5  virginica
148           6.2  virginica
149           5.9  virginica

[150 rows x 2 columns]